# Generated by Django 5.0.14 on 2026-09-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='calendarreminder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('editor', 'Editor')], default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='calendarreminder',
            constraint=models.UniqueConstraint(fields=('festival', 'reminder_days'), name='unique_festival_reminder'),
        ),
    ]
