# Generated by Django 5.0.14 on 2026-09-11 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyVideoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='baby_templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateTimeField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('card_image', models.ImageField(upload_to='festival/cards/')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('message_1', models.TextField(blank=True)),
                ('message_2', models.TextField(blank=True)),
                ('message_3', models.TextField(blank=True)),
                ('message_4', models.TextField(blank=True)),
                ('theme_color', models.CharField(default='#ff9800', max_length=20)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='festival/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='festival/images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='festival/images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='festival/images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='festival/images/')),
                ('music', models.FileField(blank=True, null=True, upload_to='festival/music/')),
                ('animation', models.CharField(choices=[('confetti', 'Confetti'), ('glitter', 'Glitter'), ('fireworks', 'Fireworks')], default='confetti', max_length=20)),
                ('custom_css', models.TextField(blank=True)),
                ('custom_js', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='festival/backgrounds/')),
            ],
        ),
        migrations.CreateModel(
            name='BabyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('festival', models.CharField(blank=True, max_length=100)),
                ('script', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='generated_baby_videos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('current_step', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baby_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wishes.babyvideotemplate')),
            ],
        ),
        migrations.CreateModel(
            name='WishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(blank=True, max_length=100)),
                ('receiver_photo', models.ImageField(blank=True, null=True, upload_to='wishes/photos/')),
                ('wish_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ai_message', models.TextField(blank=True, null=True)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('festival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='wishes.festival')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
